repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1  # Use the latest revision
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 23.12.0  # Use the specific version you want
    hooks:
      - id: black
        language_version: python3.11  # Specify your Python version

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2  # Use the specific version you want
    hooks:
      - id: isort
        language_version: python3.11  # Specify your Python version
